acme_blog:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /

# acme_test:
#     resource: "@AcmeTestBundle/Resources/config/routing.yml"
#     prefix:   /

# acme_hello:
#     resource: "@AcmeHelloBundle/Resources/config/routing.yml"
#     prefix:   /

acme_blog:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /

